"use client";
import { CalendarDays, Menu, Plus } from "lucide-react";
import { Badge } from "@/shared/ui/badge";
import { Button } from "@/shared/ui/button";
import { Dialog, DialogPopup, DialogTitle, DialogTrigger } from "@/shared/ui/dialog";
import { EmptyState, FeedbackPanel, PageHeader, Pagination, PrototypeCard } from "@/shared/ui/prototype-patterns";
import { Select } from "@/shared/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/ui/table";

export type Role = "owner" | "admin" | "staff";
export type AdminScreen = "access" | "tenant" | "agenda" | "appointments" | "customers" | "services" | "team" | "availability" | "members" | "settings";
export type PrototypeState = "ready" | "loading" | "empty" | "error" | "forbidden" | "suspended" | "not_found" | "conflict";
const nav: { screen: AdminScreen; label: string }[] = [{ screen: "agenda", label: "Agenda" }, { screen: "appointments", label: "Appointments" }, { screen: "customers", label: "Clientes" }, { screen: "services", label: "Serviços" }, { screen: "team", label: "Equipe" }, { screen: "availability", label: "Disponibilidade" }, { screen: "members", label: "Membros" }, { screen: "settings", label: "Configurações" }];

function Shell({ children, screen, role }: { children: React.ReactNode; screen: AdminScreen; role: Role }) {
  const links = nav.filter((item) => role !== "staff" || ["agenda", "appointments", "availability"].includes(item.screen));
  const list = <nav aria-label="Navegação principal" className="grid gap-1">{links.map((item) => <Button key={item.screen} variant={item.screen === screen ? "secondary" : "ghost"} className="justify-start">{item.label}</Button>)}</nav>;
  return <main className="min-h-screen p-3 sm:p-5"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-[13rem_minmax(0,1fr)]"><aside className="hidden rounded-2xl border bg-card p-3 shadow-card md:block"><div className="mb-6 flex items-center gap-2 px-2 font-semibold"><CalendarDays className="text-primary" /> Studio Sol</div>{list}</aside><header className="flex items-center justify-between md:hidden"><b>Studio Sol</b><Dialog><DialogTrigger render={<Button variant="outline" aria-label="Abrir navegação"><Menu /></Button>} /><DialogPopup><DialogTitle>Navegação</DialogTitle>{list}</DialogPopup></Dialog></header><section className="min-w-0 rounded-2xl border bg-card p-4 shadow-card sm:p-6">{children}</section></div></main>;
}
function State({ state }: { state: PrototypeState }) { if (state === "loading") return <div className="grid gap-3 animate-pulse"><div className="h-10 rounded bg-muted" /><div className="h-72 rounded bg-muted" /></div>; if (state === "empty") return <EmptyState />; if (state === "forbidden") return <FeedbackPanel kind="forbidden" title="Acesso negado" description="Sua função não permite visualizar este recurso." />; if (state === "error") return <FeedbackPanel title="Não foi possível carregar" description="Tente novamente. Não alteramos seus filtros." />; if (state === "suspended") return <FeedbackPanel kind="warning" title="Tenant suspenso" description="Fale com o proprietário para reativar o acesso." />; if (state === "not_found") return <FeedbackPanel kind="warning" title="Recurso inexistente" description="Ele pode ter sido removido ou o endereço está incorreto." />; if (state === "conflict") return <FeedbackPanel kind="warning" title="Não foi possível concluir a ação" description="O appointment mudou de estado. Atualize a lista e tente novamente." />; return null; }
function Filters() { return <div className="grid gap-2 sm:grid-cols-3"><Select aria-label="Período"><option>Esta semana</option></Select><Select aria-label="Calendário"><option>Todos os calendários</option></Select><Select aria-label="Status"><option>Agendados</option></Select></div>; }
function Agenda({ role }: { role: Role }) { const days = role === "staff" ? ["Hoje"] : ["Seg 13", "Ter 14", "Qua 15", "Qui 16", "Sex 17"]; return <><PageHeader title="Agenda" description={`Exibindo em America/Fortaleza · visão ${role === "staff" ? "diária" : "semanal"}.`} action={<Button>Hoje</Button>} /><div className="mt-5"><Filters /></div><div className="mt-5 grid gap-2 overflow-x-auto" style={{ gridTemplateColumns: `repeat(${days.length}, minmax(9rem, 1fr))` }}>{days.map((day, i) => <PrototypeCard key={day} title={day}><div className="grid gap-2"><button className="rounded-lg bg-primary/15 p-3 text-left text-sm focus-visible:ring-3 focus-visible:ring-ring"><b>09:15</b><br />Marina · Corte solar</button>{i === 1 && <button className="rounded-lg bg-secondary p-3 text-left text-sm"><b>14:00</b><br />João · Coloração</button>}</div></PrototypeCard>)}</div></>; }
function Listing({ title, customers = false }: { title: string; customers?: boolean }) { return <><PageHeader title={title} description="Use filtros para encontrar o que precisa." action={<Button><Plus /> {customers ? "Novo cliente" : "Novo"}</Button>} /><div className="mt-5"><Filters /></div><div className="mt-5 hidden overflow-hidden rounded-xl border sm:block"><Table><TableHeader><TableRow><TableHead>{customers ? "Cliente" : "Horário"}</TableHead><TableHead>Serviço</TableHead><TableHead>Status</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{["Marina Costa", "João Ribeiro", "Ana Souza"].map((name, i) => <TableRow key={name}><TableCell>{customers ? name : `14/07 · 0${9 + i}:15`}</TableCell><TableCell>{customers ? "3 appointments" : "Corte solar"}</TableCell><TableCell><Badge variant={i === 1 ? "secondary" : "outline"}>{i === 1 ? "completed" : "scheduled"}</Badge></TableCell><TableCell><Button variant="ghost">Ver detalhe</Button></TableCell></TableRow>)}</TableBody></Table></div><div className="mt-5 grid gap-3 sm:hidden">{["Marina Costa", "João Ribeiro"].map((name) => <PrototypeCard key={name} title={name} description="Corte solar · 14/07 às 09:15"><Button variant="outline">Ver detalhe</Button></PrototypeCard>)}</div><div className="mt-5"><Pagination /></div></>; }
function Services() { return <><PageHeader title="Serviços" description="Preços são armazenados em centavos." action={<Button><Plus /> Criar serviço</Button>} /><div className="mt-5 grid gap-3">{["Corte solar · 45 min · R$ 80,00", "Coloração aurora · 90 min · R$ 160,00"].map((x, i) => <PrototypeCard key={x} title={x} description={i ? "Inativo" : "Ativo"}><Button variant="outline">Editar</Button></PrototypeCard>)}</div><p className="mt-4 text-sm text-muted-foreground">Validação: duração deve ser múltipla de 15; preço é inteiro em centavos.</p></>; }
function Team() { return <><PageHeader title="Equipe e calendários" action={<Button><Plus /> Criar colaborador</Button>} /><div className="mt-5 grid gap-3 md:grid-cols-2"><PrototypeCard title="Lia Martins" description="Calendar 1:1 · America/Fortaleza"><Badge>Usuário vinculado</Badge><p className="mt-3 text-sm">Serviços: Corte solar, Barba e acabamento</p></PrototypeCard><PrototypeCard title="Rafa Nogueira" description="Calendar 1:1 · sem login"><Badge variant="outline">Sem acesso ao painel</Badge></PrototypeCard></div></>; }
function Availability() { return <><PageHeader title="Disponibilidade" description="Grade de 15 minutos · America/Fortaleza" action={<Button>Salvar regras</Button>} /><div className="mt-5 grid grid-cols-[4rem_repeat(5,minmax(5rem,1fr))] gap-1 overflow-x-auto text-sm"><span />{"Seg Ter Qua Qui Sex".split(" ").map((d) => <b key={d} className="p-2 text-center">{d}</b>)}{"08:00 08:15 08:30 08:45 09:00 09:15".split(" ").map((t, row) => <><span key={t} className="p-2 text-muted-foreground">{t}</span>{[0,1,2,3,4].map((col) => <button key={`${t}-${col}`} className={`h-9 rounded ${row > 1 && row < 5 ? "bg-primary/20 hover:bg-primary/35" : "bg-muted"}`} aria-label={`${t}, ${col + 1}`} />)}</>)}</div><p className="mt-4 text-sm text-muted-foreground">Seleção e drag são apenas visuais neste contrato; intervalo inválido mostra feedback ao salvar.</p></>; }
function Members({ role }: { role: Role }) { return <><PageHeader title="Membros" description={role === "owner" ? "Gerencie acesso ao tenant." : "Somente leitura para administradores."} action={role === "owner" ? <Button><Plus /> Adicionar usuário existente</Button> : undefined} /><div className="mt-5 grid gap-3">{["Lia Martins · owner", "Carlos Silva · admin", "Rafa Nogueira · staff"].map((x) => <PrototypeCard key={x} title={x} description="Usuário existente"><Button variant="outline" disabled={role !== "owner"}>Alterar função</Button></PrototypeCard>)}</div><p className="mt-4 text-sm text-muted-foreground">Remover o último owner retorna o conflito <code>last_owner</code>.</p></>; }
function Settings({ role }: { role: Role }) { return <><PageHeader title="Configurações do tenant" description="Studio Sol Nascente · America/Fortaleza · BRL" action={<Button disabled={role !== "owner"}>Salvar alterações</Button>} /><div className="mt-5 grid gap-3"><PrototypeCard title="Nome" description="Studio Sol Nascente" /><PrototypeCard title="Timezone" description="America/Fortaleza" /><PrototypeCard title="Moeda" description="BRL" /></div></>; }
export function AdminMvpPrototype({ screen = "agenda", role = "owner", state = "ready" }: { screen?: AdminScreen; role?: Role; state?: PrototypeState }) { if (screen === "access") return <main className="grid min-h-screen place-items-center p-4"><PrototypeCard title="Conectando sua conta" description="Você será redirecionado ao Keycloak. Não usamos senha nesta aplicação."><Button>Continuar com Keycloak</Button></PrototypeCard></main>; if (screen === "tenant") return <main className="grid min-h-screen place-items-center p-4"><PrototypeCard title="Escolha um tenant" description="Você tem acesso a mais de um negócio."><div className="grid gap-2"><Button variant="outline">Studio Sol Nascente</Button><Button variant="outline">Barbearia Lua</Button></div></PrototypeCard></main>; return <Shell screen={screen} role={role}>{state === "ready" ? <>{screen === "agenda" && <Agenda role={role} />}{screen === "appointments" && <Listing title="Appointments" />}{screen === "customers" && <Listing title="Clientes" customers />}{screen === "services" && <Services />}{screen === "team" && <Team />}{screen === "availability" && <Availability />}{screen === "members" && <Members role={role} />}{screen === "settings" && <Settings role={role} />}</> : <State state={state} />}</Shell>; }
